name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Prepare
        run: |
          pacman-key --init
          pacman -Syu --noconfirm
          pacman -S --noconfirm git meson clang glslang libcap wlroots \
            sdl2 vulkan-headers libx11 libxmu libxcomposite libxrender libxres \
            libxtst libxkbcommon libdrm libinput wayland-protocols benchmark \
            xorg-xwayland pipewire cmake \
            libavif libheif aom rav1e libdecor libxdamage
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build with gcc
        run: |
          export CC=gcc CXX=g++
          meson build-gcc/ --werror --auto-features=enabled
          ninja -C build-gcc/
      - name: Build with gcc (no vr)
        run: |
          export CC=gcc CXX=g++
          meson build-gcc-novr/ -Denable_openvr_support=false --werror --auto-features=enabled
          ninja -C build-gcc-novr/
      - name: Build with clang
        run: |
          export CC=clang CXX=clang++
          meson build-clang/ --werror --auto-features=enabled
          ninja -C build-clang/
